### PR TITLE
Argument supports NSProxy and its subclasses

### PR DESCRIPTION
**Pull request by flexih**

### CODE REVIEW

**Comment by johnno1962** [comment]
Thanks, Are you you getting a crash? You can't do id.isKind(of: NSProxy.self)?

**Review by johnno1962 — APPROVED** [review]
Almost there, Can you move the added test to the start of the block before the thread stuff please? Also, have you tried returning the string from the `identify` function instead of nil so the remainder of arguments can be processed?

**Comment by flexih** [comment]
> Thanks, Are you you getting a crash? You can't do id.isKind(of: NSProxy.self)?

Yes, it crashes, because NSProxy does not implement isKind(of:).

**Review by johnno1962 — APPROVED** [review]
Perfect, thanks a lot for this fix. Merging now.

**Pull request merged**
